config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :items do
    member do
      patch :purchased
    end
    member do
      patch :unpurchased
    end
  end
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, inclusion: { in: ["accessories", "beauty", "books", "clothing", "electricals", "fitness", "footwear", "gardening", "gifts", "homeware", "makeups", "music", "pets", "sports", "travel"] }
  CATEGORIES = ["accessories", "beauty", "books", "clothing", "electricals", "fitness", "footwear", "gardening", "gifts", "homeware", "makeups", "music", "pets", "sports", "travel"]
  # ['small', 'medium', '...' ]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates  :item_url, presence: true
  # validates :item_url, uniqueness: { message: "item exists already!" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
  has_many :categories, through: :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :find_category, only: [:update, :edit, :destroy]

  def index
    @categories = Category.all
  end

  # def new
  #   @category = Category.new
  # end

  # def create
  #   @category = Category.new(category_params)
  #   @category.save
  #   redirect_to items_path
  # end

  # def edit
  # end

  # def update
  #   if @category.update(category_params)
  #     redirect_to categories_path
  #   else
  #     render :index
  #   end
  # end

  # def destroy
  #   @category.destroy
  #   redirect_to items_path
  # end


  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: %i[update edit show destroy category purchased unpurchased]
  before_action :scrape, only: [:create]

  def index
    @categories = Category::CATEGORIES
    if params[:sort].present?
      @items = Item.all.order(params[:sort])
    elsif params[:purchased].present?
      @items = Item.where(purchased: true)
    elsif params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @items = Item.where(sql_query, query: "%#{params[:query]}%")
    elsif params[:filter].present?
      if params[:filter] == "purchased"
        @items = Item.where(purchased: true)
      else
        category = Category.find_by(name: params[:filter])
        @items = Item.where(category: category)
      end
    else
      @items = Item.all
    end
    @items_count = Item.count
  end

  def new
    @item = Item.new
  end

  def show
  end

  def create
    @item = Item.new(@attributes)
    @item.user = current_user
    @category = Category.find(params[:item][:category_id])
    @item.category = @category
    if @item.save!
      @item.save!
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      # redirect_to item_path(@item)
      redirect_to items_path
    else
      render :index
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  def purchased
    @item.update(purchased: true)
    @item.save!
    redirect_to items_path
  end

  def unpurchased
    @item.update(purchased: false)
    @item.save!
    redirect_to items_path
  end


  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:category_id, :item_url, :sort, :name, :created_at, :price, :original_price,
                                 :purchased, :description)
  end

  def scrape
    @url = params[:item][:item_url]
    html_file = URI.open(@url, "Accept-Language" => "en-US").read
    html_doc = Nokogiri::HTML(html_file)

    if @url.include?('etsy')
      name = html_doc.search('.wt-text-body-03.wt-line-height-tight.wt-break-word').text.strip.split(/[.,\-]/).first
      description = html_doc.search("#product-details-content-toggle > div > ul").text.strip
      currency = html_doc.search('.wt-text-title-03.wt-mr-xs-2').text.strip.match(/[£€]/).to_s
      price = html_doc.search('.wt-text-title-03.wt-mr-xs-2').text.strip.match(/\d+.\d{2}/).to_s.sub(".", "").to_i
      original_price = html_doc.search('.wt-text-strikethrough.wt-text-caption.wt-text-gray.wt-mr-xs-1').text.strip.match(/\d+.\d{2}/).to_s.sub(
        ".", ""
      ).to_i
      elements = []
      html_doc.search('.wt-max-width-full.wt-horizontal-center.wt-vertical-center.carousel-image.wt-rounded').first(3).each do |element|
        image = element["data-src-zoom-image"]
        elements << image
      end
      image_url = elements
      # ignore

      @attributes = {
        name: name,
        item_url: @url,
        price: price,
        description: description,
        image_url: image_url,
        original_price: original_price,
        currency: currency
      }

    else
      # Mytheresa
      name_brand = html_doc.search('.product-designer span a').text.strip
      name_product = html_doc.search('.product-name span').text.strip
      name = "#{name_brand} | #{name_product}"
      if html_doc.search('.pa1.product-description').present?
        description = html_doc.search('.pa1.product-description').text.strip
      else
        description = html_doc.search('.pa1-rmm.product-description').text.strip
      end
      if html_doc.search('.price-box .special-price .price').present?
        currency = html_doc.search('.price-box .special-price .price').text.strip.match(/[£€]/).to_s
      else
        currency = html_doc.search('.price-box .regular-price .price').text.strip.match(/[£€]/).to_s
      end
      if html_doc.search('.price-box .special-price .price').present?
        price = html_doc.search('.price-box .special-price .price').first.text.strip.chars.select do |x|
          x.to_i.to_s == x
        end.join.to_i * 100
      else
        price = html_doc.search('.price-box .regular-price .price').first.text.strip.chars.select do |x|
          x.to_i.to_s == x
        end.join.to_i * 100
      end
      if html_doc.search('.price-box .old-price .price').present?
        original_price = html_doc.search('.price-box .old-price .price').first.text.strip.chars.select do |x|
          x.to_i.to_s == x
        end.join.to_i * 100
      end
      elements = []
      html_doc.search('.gallery-image').first(3).each do |element|
        image = "https:#{element['src']}"
        elements << image
      end
      image_url = elements

      if price.negative?
        @attributes = {
          name: name,
          item_url: @url,
          price: original_price,
          description: description,
          image_url: image_url
          # original_price: original_price
        }
      else
        @attributes = {
          name: name,
          item_url: @url,
          price: price,
          description: description,
          image_url: image_url,
          original_price: original_price,
          currency: currency
        }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 

end

app/views/items/_form.html.erb
<%= simple_form_for [category, item] do |f| %>
  <%= f.association :category, label: 'Bookmark category', class: 'add-text' %>
  <%= f.input :item_url, label: 'Bookmark link', class: 'add-text' %>
  <%= f.submit 'Create bookmark', class: 'btn btn-primary', id: 'add-update-item' %>
<% end %>

app/views/items/edit.html.erb
<div class="container-edit">
  <div class="form-group-edit">
    <h1>Change Category</h1>
    <div class="form-item-edit">
      <%# <%= render "form", category: @category, item: @item %>
      <%= simple_form_for [@category, @item] do |f| %>
      <%= f.association :category %>
      <%# <%= f.input :item_url %>
      <%= f.submit 'Update category', class: 'btn btn-primary', id: 'add-update-item' %>
      <% end %>
  </div>
  <%= link_to "Back to Bookmarks", items_path, class: "btn btn-ghost-edit" %>
</div>
</div>

app/views/items/index.html.erb
<div class="top-container">
  <%# // Welcome message %>
  <div class="welcome-info">
    <h3>Hello <%= current_user.first_name %> ☺ </h3>
    <h4>You have <%= pluralize @items_count, 'saved Bookmark' %></h4>
  </div>
</div>

<div class="mid-container">
  <%# // search form starts here %>
  <div class="search-bar">
    <%= form_tag items_path, method: :get do %>
      <div class="search-form-control form-group">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search ..."
        %>
        <button name="button" type="submit" class="btn btn-ghost-search">
        <%# <%= submit_tag "Go!", class: "btn btn-primary btn-sm" %>
          <%# <i class="fas fa-search"></i> %>
        </button>
      </div>
    <% end %>
  </div>
  <div class="create-sort">
    <%# // sort form starts here %>
    <div class="sort-form-ghost">
      <%= form_tag items_path, method: :get do  %>
        <div class="sort-form-control form-group">
          <%= select_tag(:sort, options_for_select([["Alphabetical", :name],["Lowest Price", :price],["Oldest",:created_at]], params[:sort]), {prompt: "Sort By", onchange: "this.form.submit()"})%>
        <%# <%= submit_tag "Sort", class: "btn btn-primary"%>
            </div>
        <% end %>
    </div>
    <%# // Create button %>
    <div class="item-create">
      <%= link_to '+Add', new_item_path, class: 'btn btn-ghost-item' %>
    </div>
  </div>
</div>

<div class="content-container">
  <%# // sidebar %>
  <div class="row row-width">
    <div class="sidebar col-3">
      <%= link_to "All (#{Item.count})", items_path, class: "btn btn-category #{"active" unless params[:filter]}" %>
      <%= link_to "Purchased (#{Item.where(purchased: true).count})", items_path(filter: :purchased), class: "purchase-text #{"active" if params[:filter] == 'purchased' }" %>
      <% @categories.each do |category| %>
       <%= link_to "#{category.capitalize} (#{Item.where(category: Category.where(name: category)).count})", items_path(sort: params[:sort], query: params[:query], filter: category,), class: "btn btn-category #{"active" if params[:filter] == category }" %>
      <% end %>
    </div>

  <%# // The Cards are coded below %>
    <div class="item-cards col-9">
      <% @items.each do |item| %>
      <%# // Main body of the cards starts here; only showing the first image %>
        <div class="item-card">
          <%# <img src== item.image_url.first class="card-img-top img-responsive img-fluid" height="250px"> %>
            <div class="card-top">
              <img src=<%= item.image_url.first %> class="item-image">
              <div class="item-image-overlay">
                <button type="button" class="button-more" data-toggle="modal" data-target="#<%= dom_id(item) %>">
                <p>Quick view</p></button>
              </div>
            </div>
            <%# // This is the More section %>
            <%# // This is the code for the More button popup window %>
            <div class="modal fade" id="<%= dom_id(item) %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="item-detail-title"><%= item.name %></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="item-details">
                      <%# // Caroussel for the popup "more info window %>
                      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img class="d-block w-30" src=<%= item.image_url[0] %> alt="First slide">
                          </div>
                          <div class="carousel-item">
                            <img class="d-block w-30" src=<%= item.image_url[1] %> alt="Second slide">
                          </div>
                          <div class="carousel-item">
                            <img class="d-block w-30" src=<%= item.image_url[2] %> alt="Third slide">
                          </div>
                          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div>
                        <%# // end of code for caroussel %>
                        <h4 class="item-description"><%= item.description %><h4>
                        <%# <h4 class="item-price"><%= item.price<h4> %>
                        <h4 class="item-price"><%= "#{item.currency}#{'%.2f' % (item.price.to_f/100).to_s}" %> <s> <%= (item.original_price.to_i)>0 ? "#{item.currency}#{'%.2f' % (item.original_price.to_f/100).to_s}" : ""%></s>  </h4>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <a class="btn btn-web" href="<%= item.item_url %>" target="_blank" >Go website</a>
                      <button type="button" class="btn btn-back" data-dismiss="modal">Back</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <%# // end more info section %>

        <div class="card-body">
          <h5 class="card-title"><%= item.name.truncate(24) %></h5>
          <h5 class="card-price"><%= "#{item.currency}#{'%.2f' % (item.price.to_f/100).to_s}" %> <s> <%= (item.original_price.to_i)>0 ? "#{item.currency}#{'%.2f' % (item.original_price.to_f/100).to_s}" : ""%> </s> </h5>
          <div class="card-category">
            <i class="fas fa-tags"></i>
            <p><%= item.category.name.capitalize %></p>
          </div>
        </div>

        <div class="card-footer">
          <%# // Footer with all the buttons starts here %>

          <%# // delete button %>
          <div class="delete-button">
            <%= link_to "", item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash-alt" %>
            <%# <%= link_to "Delete", item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash-alt" %>
          </div>
          <%# // end of delete button %>

          <%# // Change Button %>
          <div class="modify-button">
            <%= link_to '', edit_item_path(item), class: "fas fa-pencil-alt" %>
          </div>
          <div class="purchase-confirm">
            <%# <i class="fa fa-shopping-cart"></i> %>
            <% if item.purchased == false || item.purchased == nil %>
              <%= link_to 'Buy?', purchased_item_path(item), method: :patch, data: { confirm: 'Confirm your purchase' }, class: "btn btn-buy" %>
            <% else %>
              <%= link_to 'Bought', unpurchased_item_path(item), method: :patch, data: { confirm: 'Confirm you have not bought this item' }, class: "btn btn-bought" %>
            <% end %>
          </div>
          <%# // End of change button %>
          
          <%# // The Buy button starts here %>
          <%# <button type="button" class="btn btn-buy" data-toggle="modal" data-target="#exampleModal2">
            Buy</button>
            <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header purchase-confirm">
                    <h5 class="modal-title" id="purchase">Purchase Confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%# ** Thank you for your purchase ** <p></p><p>
                    Your item is on it's way.</p> %>
                    <%# <%= link_to "Confirmed", purchased_item_path(item.id), method: :patch, class:"btn btn-confirm-yes" %>
                    <%# <button type="button" class="btn btn-confirm-no" data-dismiss="modal">Not yet</button> %>
                  <%# </div>
                  <div class="modal-footer purchase-confirm">
                    <button type="button" class="btn btn-back" data-dismiss="modal">Back</button>
                  </div>
                </div> %>
              <%# </div>
            </div> %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container-new">
  <div class="form-group-new">
    <h1>Add a Bookmark</h1>
    <div class="form-item-new">
      <%= render "form", category: @category, item: @item %>
    </div>
    <%=  link_to "Back to Bookmarks", items_path, class: "btn btn-ghost-new" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag %>
    <title>BOOKMARK - the handy app to save all of your favorite shopping items in one place</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="min-height: calc(100vh - 110px)" >
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hpg-content-container">
  <div class="row home row-width">
      <div class="left col-4">
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dajifvnn5/image/upload/v1647190865/heidi-fin-2TLREZi7BUg-unsplash_peszmk.jpg);">
        </div>
      </div>
      <div class="middle col-4">
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dajifvnn5/image/upload/v1645110270/Shopping_screen_mxaypo.jpg);">
        </div>
      </div>
      <div class="right col-4">
          <h1>Get right to <br>the stuff you want</h1>
          <h5>Create your own private shopping gallery with all the items you like</h5>
          <% if user_signed_in? %>
            <%= link_to "My bookmarks", items_path, class:"btn btn-bookmark" %>
          <% else %>
            <%= link_to "Get started", new_user_registration_path, class:"btn btn-start" %>
            <p>Already have an account? <%= link_to "Log in", new_user_session_path, class:"btn-login" %></p>
          <% end %>
      </div>
  </div>
</div>

<div class="block-container">
  <%# <div class="row block-row"> %>
    <h3 class="block-title">With BOOKMARK</h3>
    <div class="block-cards">
      <div class="block-card">
        <div class="block-card-content">
          <img src="https://res.cloudinary.com/dajifvnn5/image/upload/c_scale,w_56/v1647350327/laptop_cow5lt.png" class="block-card-image">
          <h5>Save items across different websites</h5>
        </div>
      </div>
      <div class="block-card">
        <div class="block-card-content">
          <img src="https://res.cloudinary.com/dajifvnn5/image/upload/c_scale,w_56/v1647350576/tag_qvhtsl.png" class="block-card-image">
          <h5>Compare similar items</h5>
        </div>
      </div>
      <div class="block-card">
        <div class="block-card-content">
          <img src="https://res.cloudinary.com/dajifvnn5/image/upload/c_scale,w_56/v1647350380/internet_itb7hb.png" class="block-card-image">
          <h5>Find the best deal</h5>
        </div>
      </div>
      <div class="block-card">
        <div class="block-card-content">
          <img src="https://res.cloudinary.com/dajifvnn5/image/upload/c_scale,w_56/v1647349843/team_qqasyr.png" class="block-card-image">
          <h5>Share with friends and families</h5>
        </div>
      </div>
    </div>
  </div>


<%# <div class="home-container">
  <div class="tagline">
    <div class="text-content">
      <h1>BOOKMARK</h1>
      <h5>It has never been so easy to manage your shopping basket!</h5>
      <br>
      <p> > Save items across different websites <p>
      <p> > Compare similar items</p>
      <p> > Find the best deals </p>
      <p> > Share with friends and family </p>
    </div>
    <div class="start">
      <%= link_to "Get Started", items_path, class:"btn btn-outline-secondary btn-start" %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a class="foot-link" href="#"><i class="fab fa-instagram"></i></a>
    <a class="foot-link" href="#"><i class="fab fa-facebook"></i></a>
    <a class="foot-link" href="#"><i class="fab fa-twitter"></i></a>
    <a class="foot-link" href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyrights">
    <a class="footer-copyright" href="#">About us</a>
    <a class="footer-copyright" href="#">Terms</a>
    <a class="footer-copyright" href="#">Privacy</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm  navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <img src="https://res.cloudinary.com/dajifvnn5/image/upload/v1647089917/bookmark_2_bogdxy.png">
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%# <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        <%# </li> %>
        <li class="nav-item">
          <%= link_to "My Bookmarks", items_path, class: "nav-link" %>
        </li>
        <%# <li class="nav-item">
          <%= link_to "Add Item", new_item_path(@item), class: "nav-link" %>
        <%# </li> %>


        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/dajifvnn5/image/upload/c_thumb,w_200,g_face/v1647089905/user_opfmpc.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" id="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= current_user.first_name %> <%= current_user.last_name %>
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%# <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        <%# </li> %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>